#!/usr/bin/env bash

set -euo pipefail

usage() {
  echo "Usage: ./run find [GoogleDriveFolderURL]"
}

if [[ "$#" -lt 1 || "$#" -gt 2 || "$1" != "find" ]]; then
  usage
  exit 1
fi

if [[ "$#" -eq 2 ]]; then
  python3 main.py "$2"
else
  python3 main.py
fi
